image: node:10

cache:
  paths:
  - node_modules/

pages:
  before_script:
  - node -v
  # - NPM_CONFIG_LOGLEVEL=warn
  - npm install --production
  script:
  - npm test
  - mv out public
  artifacts:
    paths:
    - public
  only:
  - master
