sudo: false

git:
  depth: 3

branches:
  only:
    - master

language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

before_script:
  - npm prune
  - npm dedupe

after_success: script/github

env:
  global:
  - DEPLOY_NAME="Travis CI Deployer"
  - DEPLOY_EMAIL="deployer@travis-ci.org"
  - secure: K/oEpk5v5gW2sf22d6Gzu2/ZQb5miqLrZOywMQsLNv6lbKM/0gRvMdc0Q39JEYnCFFtqG+lfY2CY6eE7EGz9gWgwOFyFSFNyW9los9VaJ9Hn/J8fdLOIfNIhXeHbfqJLF4W8iA5NqgrFBDP2Pw2BU4MwGPOuVYpjQLbS340AvYfTNdaukubXyjqinmBLnVOEC8Ucxv7piqozzadGxZU2JmLY3LJrkYz+GZuQdNgTEYkZTWGtp6l3OQCkO26AzWjmnlSh6rJpruy2A5L/nJyfCR6vQq6xilbN4id1CHGXB4a/u5nvyuN0DlX1XZ02a1x9f4eXLhtRqpgeQIOlNIam7zDZKPw9a+cn6GypW9Ulec2+ixru4Fbp8MiF+xIlp52CgANyNBmyR1VX1cLE9qQ6ikWVdqMw869A71028jWDwRQihDgIDymOapGaOK2E7Yl0Xd+4JOg1lNL/HoRhRAwYPZlTiNf1AWyIVO2DWnZSdimBnvt+vzUC3mbKSxFOfwdN/89TW6Q5U/SXOatGfpwzkAJeZasmmsoPdPdlsUj9GTA8YOl8muNthCmswrtUMwKgAtNx+AQbe/ieXBxxLxngXBkNGlg2t3ApFwRIukcMejxCUG5fmW/6WAOWGR18GR0FGqSwoiXyUJ9dCpe+e+e5zI9jHrOqj1/6dd7632111u8=
  - secure: nVDJ57SgTIfAR9UkNUJcBHakCHBbiz/VMHReotKQ5kakr14h8l1uISvDp4+1A5aWTODl7JAs8i9YACumWUY/KFiwaOluCRQUXfOrxUwcKqrBw32hh086+CvloJtkUrkyb6w0x6Yn/1CRdYwTscKO/4myJsd4r2GdD+bTCU8YObN1N0AqykSflOTSJmFVoU79Qp6j3AZodoR/xJMn7aMzelrclQMJ570Iyqb/3qQJ/RIF7XQk+Q09FaLyV5+qCezJFG6VRcW2wPn7iXDGWu/R59MrXdkbT/QtGq+0tCTogmp1W8RbgltZLUnY2Oab2oOqEKXB2LphYbjgfXemgzS6ZZEyotDQMLJAA25cw+hUzPfKx/CSl5K/IJCcFjqMkRvbto8yie95uA+yUN+YoeMv5nTEK1zF5umrWWHfHRTybojAR6oM5hmSfVAO0c3RevyCy73FMXTTxW2wnqArD7wgLso4QfBG6vcGOIlLh96OsITB2GD4/t+KYjFcg3+JRKd0Qt/qddzGoBV0/Cb7Ml3bWqpoFYrfxANSkoAYprKe46+p5V6q5b2vDnltI0ccK6mgkFbWuPH2miX+5sUCAP3Apige8hTmqOwzBI/8jcbloQTYDbZFlSYWFzUHfWkmRltromOlL4tcRu+9z5A5RAWDAaYcLmAsIXL7TEApT18Akek=
