encoding: utf-8
exclude:
- README.md
- CNAME
- FarMenu.ini
- node_modules
- out
include:
- .ssh
defaults:
- scope:
    path: "" # empty string for all files
  values:
    layout: "default"
sass:
  style: :compressed
