encoding: utf-8
exclude:
- README.md
- CNAME
- FarMenu.ini
include:
- .well-known
defaults:
- scope:
    path: "" # empty string for all files
  values:
    layout: "default"
sass:
  style: :compressed
